{
 "title": "Sync",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Success QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync/once/success.timer",
     "query": "SELECT mean(\"m1\") AS \"m1\",mean(\"m5\") AS \"m5\",mean(\"m15\") AS \"m15\" FROM \"autogen\".\"sync/once/success.timer\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync/once/failure.timer",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Success latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync/once/success.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync/once/failure.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Batch size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Batch logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sync/once/size.histogram",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}