// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts/{address}/txs": {
            "get": {
                "description": "Query storage transactions for specified account, support root hash filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Account's storage transaction list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The submitter address of the uploaded file",
                        "name": "address",
                        "in": "path"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "The number of skipped records, usually it's pageSize * (pageNumber - 1)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "The number of records displayed on the page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "The merkle root hash of the uploaded file",
                        "name": "rootHash",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.StorageTxList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/stats/fee": {
            "get": {
                "description": "Query fee statistics, including incremental and full data, and support querying at hourly or daily time intervals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "Storage fee statistics",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "The number of skipped records, usually it's pageSize * (pageNumber - 1)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "maximum": 2000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "The number of records displayed on the page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "minTimestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "maxTimestamp",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "hour",
                            "day"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "Statistics interval",
                        "name": "intervalType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort by timestamp",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.FeeStatList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/stats/layer1-tx": {
            "get": {
                "description": "Query transaction statistics, including incremental and full data, and support querying at hourly or daily time intervals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "Layer1 transaction statistics",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "The number of skipped records, usually it's pageSize * (pageNumber - 1)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "maximum": 2000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "The number of records displayed on the page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "minTimestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "maxTimestamp",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "hour",
                            "day"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "Statistics interval",
                        "name": "intervalType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort by timestamp",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.TxStatList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/stats/storage": {
            "get": {
                "description": "Query data storage statistics, including incremental and full data, and support querying at hourly or daily time intervals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "Data storage statistics",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "The number of skipped records, usually it's pageSize * (pageNumber - 1)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "maximum": 2000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "The number of records displayed on the page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "minTimestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Timestamp in seconds",
                        "name": "maxTimestamp",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "hour",
                            "day"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "Statistics interval",
                        "name": "intervalType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort by timestamp",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.DataStatList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/stats/summary": {
            "get": {
                "description": "Query statistics summary includes ` + "`" + `storage fee` + "`" + ` and ` + "`" + `log sync height` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "Statistics summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.Summary"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/txs": {
            "get": {
                "description": "Query storage transactions, support address and root hash filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Storage transaction list",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "The number of skipped records, usually it's pageSize * (pageNumber - 1)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "The number of records displayed on the page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.StorageTxList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        },
        "/txs/{txSeq}": {
            "get": {
                "description": "Query storage transaction by txSeq",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Storage transaction information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "storage transaction sequence number",
                        "name": "txSeq",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/api.StorageTxDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BusinessError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "api.DataStat": {
            "description": "Storage data information",
            "type": "object",
            "properties": {
                "dataSize": {
                    "description": "Size of storage data in a specific time interval",
                    "type": "integer"
                },
                "dataTotal": {
                    "description": "Total Size of storage data by a certain time",
                    "type": "integer"
                },
                "fileCount": {
                    "description": "Number of files in a specific time interval",
                    "type": "integer"
                },
                "fileTotal": {
                    "description": "Total number of files by a certain time",
                    "type": "integer"
                },
                "statTime": {
                    "description": "Statistics time",
                    "type": "string"
                }
            }
        },
        "api.DataStatList": {
            "description": "Storage data list",
            "type": "object",
            "properties": {
                "list": {
                    "description": "Stat list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DataStat"
                    }
                },
                "total": {
                    "description": "The total number of stat returned",
                    "type": "integer"
                }
            }
        },
        "api.FeeStat": {
            "description": "Storage fee information",
            "type": "object",
            "properties": {
                "statTime": {
                    "description": "Statistics time",
                    "type": "string"
                },
                "storageFee": {
                    "description": "The base fee for storage in a specific time interval",
                    "type": "number"
                },
                "storageFeeTotal": {
                    "description": "The total base fee for storage by a certain time",
                    "type": "number"
                }
            }
        },
        "api.FeeStatList": {
            "description": "Storage fee list",
            "type": "object",
            "properties": {
                "list": {
                    "description": "Stat list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FeeStat"
                    }
                },
                "total": {
                    "description": "The total number of stat returned",
                    "type": "integer"
                }
            }
        },
        "api.StorageFeeStat": {
            "description": "Stat storage fee information",
            "type": "object",
            "properties": {
                "chargeToken": {
                    "description": "Charge token info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.TokenInfo"
                        }
                    ]
                },
                "storageFeeTotal": {
                    "description": "Total storage fee",
                    "type": "number"
                }
            }
        },
        "api.StorageTxDetail": {
            "description": "Submission transaction information",
            "type": "object",
            "properties": {
                "blockNumber": {
                    "description": "The block where the submit event is emitted",
                    "type": "integer"
                },
                "dataSize": {
                    "description": "File size in bytes",
                    "type": "integer"
                },
                "endPosition": {
                    "description": "The ending position of the file stored in the storage node",
                    "type": "integer"
                },
                "expiration": {
                    "description": "Expiration date of the uploaded file",
                    "type": "integer"
                },
                "from": {
                    "description": "File uploader address",
                    "type": "string"
                },
                "gasFee": {
                    "description": "The gas fee of the transaction on layer1",
                    "type": "integer"
                },
                "gasLimit": {
                    "description": "The gas limit of the transaction on layer1",
                    "type": "integer"
                },
                "gasUsed": {
                    "description": "The gas used of the transaction on layer1",
                    "type": "integer"
                },
                "method": {
                    "description": "The name of the submit event is always ` + "`" + `submit` + "`" + `",
                    "type": "string"
                },
                "rootHash": {
                    "description": "Merkle root of the file to upload",
                    "type": "string"
                },
                "segments": {
                    "description": "The total number of segments the file is split into",
                    "type": "integer"
                },
                "startPosition": {
                    "description": "The starting position of the file stored in the storage node",
                    "type": "integer"
                },
                "status": {
                    "description": "File upload status, 0-not uploaded,1-uploading,2-uploaded",
                    "type": "integer"
                },
                "storageFee": {
                    "description": "The storage fee required to upload the file",
                    "type": "number"
                },
                "timestamp": {
                    "description": "The block time when submit event emits",
                    "type": "integer"
                },
                "txHash": {
                    "description": "The transaction where the submit event is emitted",
                    "type": "string"
                },
                "txSeq": {
                    "description": "Submission index in submit event",
                    "type": "string"
                }
            }
        },
        "api.StorageTxInfo": {
            "description": "Submission transaction information",
            "type": "object",
            "properties": {
                "blockNumber": {
                    "description": "The block where the submit event is emitted",
                    "type": "integer"
                },
                "dataSize": {
                    "description": "File size in bytes",
                    "type": "integer"
                },
                "from": {
                    "description": "File uploader address",
                    "type": "string"
                },
                "method": {
                    "description": "The name of the submit event is always ` + "`" + `submit` + "`" + `",
                    "type": "string"
                },
                "rootHash": {
                    "description": "Merkle root of the file to upload",
                    "type": "string"
                },
                "segments": {
                    "description": "The total number of segments the file is split into",
                    "type": "integer"
                },
                "status": {
                    "description": "File upload status, 0-not uploaded,1-uploading,2-uploaded",
                    "type": "integer"
                },
                "storageFee": {
                    "description": "The storage fee required to upload the file",
                    "type": "number"
                },
                "timestamp": {
                    "description": "The block time when submit event emits",
                    "type": "integer"
                },
                "txHash": {
                    "description": "The transaction where the submit event is emitted",
                    "type": "string"
                },
                "txSeq": {
                    "description": "Submission index in submit event",
                    "type": "integer"
                },
                "uploadedSegments": {
                    "description": "The number of segments the file has been uploaded",
                    "type": "integer"
                }
            }
        },
        "api.StorageTxList": {
            "description": "Submission information list",
            "type": "object",
            "properties": {
                "list": {
                    "description": "Submission list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StorageTxInfo"
                    }
                },
                "total": {
                    "description": "The total number of submission returned",
                    "type": "integer"
                }
            }
        },
        "api.Summary": {
            "description": "Storage summary information",
            "type": "object",
            "properties": {
                "logSync": {
                    "description": "Synchronization information of submit event",
                    "allOf": [
                        {
                            "$ref": "#/definitions/stat.LogSyncInfo"
                        }
                    ]
                },
                "storageFee": {
                    "description": "Storage fee information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.StorageFeeStat"
                        }
                    ]
                }
            }
        },
        "api.TokenInfo": {
            "description": "Charge token information",
            "type": "object",
            "properties": {
                "address": {
                    "description": "The address of the token contract",
                    "type": "string"
                },
                "decimals": {
                    "description": "Token decimals",
                    "type": "integer"
                },
                "name": {
                    "description": "Token name",
                    "type": "string"
                },
                "native": {
                    "description": "True is native token, otherwise is not",
                    "type": "boolean"
                },
                "symbol": {
                    "description": "Token symbol",
                    "type": "string"
                }
            }
        },
        "api.TxStat": {
            "description": "Storage transaction information",
            "type": "object",
            "properties": {
                "statTime": {
                    "description": "Statistics time",
                    "type": "string"
                },
                "txCount": {
                    "description": "Number of layer1 transaction in a specific time interval",
                    "type": "integer"
                },
                "txTotal": {
                    "description": "Total number of layer1 transaction by a certain time",
                    "type": "integer"
                }
            }
        },
        "api.TxStatList": {
            "description": "Storage transaction list",
            "type": "object",
            "properties": {
                "list": {
                    "description": "Stat list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TxStat"
                    }
                },
                "total": {
                    "description": "The total number of stat returned",
                    "type": "integer"
                }
            }
        },
        "stat.LogSyncInfo": {
            "description": "Submit log sync information",
            "type": "object",
            "properties": {
                "layer1-logSyncHeight": {
                    "description": "Synchronization height of submit log on blockchain",
                    "type": "integer"
                },
                "logSyncHeight": {
                    "description": "Synchronization height of submit log on storage node",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "0G Storage Scan API",
	Description:      "Use any http client to fetch data from the 0G Storage Scan.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
